### ISSUE TITLE
isnt working as expected

### ISSUE THREAD

**Issue by test63464** [3ncod3/keep-mega-alive#2]
hello. the script isnt working or i guess i am doing something wrong,need help from you. please share your handle where i can ping you. wont take much of your time. Thank You

**Comment by test63464** [comment]
can u help me with it?. I can tell the issue here

**Comment by 3ncod3** [comment]
hey @test63464, just released a new version `v1.2` for macOS/Linux so try using that instead and see if that fixes your issue
